### ISSUE TITLE
Getting instance with the API

### ISSUE THREAD

**Issue by ReflexShow** [MinecraftLibraries/NPCLib#110]
`
[00:17:00 WARN]: java.lang.NullPointerException
[00:17:00 WARN]:        at theBartender.npcCommand.onCommand(npcCommand.java:27)
[00:17:00 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:17:00 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:17:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[00:17:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:17:00 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[00:17:00 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[00:17:00 WARN]:        at java.lang.Thread.run(Unknown Source)
`

npcCommand.java:27 -
`NPC npc = Main.getInstance().getNPCLib().createNPC();`

**Comment by JitseB** [comment]
I just explained in the Discord server that there's an issue template you need to use for issue tickets so I can be of best help. I know it might seems easy to just forego this template, but I can't stress enough how important those details are.

So, first question is if you would be so kind to fill that out.

Second, What does your main class look like? It seems like either the main instance or the library instance is null...
