### ISSUE TITLE
Spamming errors when NPC spawned in nether or end

### ISSUE THREAD

**Issue by ItsWind** [MinecraftLibraries/NPCLib#111]
Hope this is the right template :)

**Describe the bug**
Spawning an NPC in the nether or the end (anywhere but the overworld) will result in this error spamming the console and the NPC glitching out.

**NPCLib usage option**
Dummy plugin

**NPCLib JAR name**
E.g. npclib-plugin-2.9-SNAPSHOT.jar

**Server version**
Paper version 129 1.16.1

**To Reproduce**
Create an NPC in the nether or the end.

**Expected behavior**
uh not this.

**ERROR**:
`java.lang.IllegalStateException: Unable to find constructor for class net.minecraft.server.v1_16_R1.EntityArmorStand ([null, double, double, double]).
        at com.comphenix.tinyprotocol.Reflection.getConstructor(Reflection.java:279) ~[?:?]
        at net.jitse.npclib.hologram.Hologram.createPackets(Hologram.java:136) ~[?:?]
        at net.jitse.npclib.hologram.Hologram.<init>(Hologram.java:99) ~[?:?]
        at net.jitse.npclib.nms.v1_16_R1.NPC_v1_16_R1.getPlayerHologram(NPC_v1_16_R1.java:43) ~[?:?]
        at net.jitse.npclib.nms.v1_16_R1.NPC_v1_16_R1.sendShowPackets(NPC_v1_16_R1.java:91) ~[?:?]
        at net.jitse.npclib.internal.NPCBase.show(NPCBase.java:231) ~[?:?]
        at net.jitse.npclib.listeners.HandleMoveBase.handleMove(HandleMoveBase.java:18) ~[?:?]
        at net.jitse.npclib.listeners.PeriodicMoveListener.lambda$startTask$0(PeriodicMoveListener.java:32) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-127]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-127]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-127]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-127]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-127]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-127]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-127]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by skylerush** [comment]
are you able to spawn NPC's in the normal world?

**Comment by ItsWind** [comment]
Yes

**Comment by skylerush** [comment]
Odd I will try my self , try to spawn without holograms and let me know

**Comment by skylerush** [comment]
To spawn without holograms keep the texts null

**Comment by JitseB** [comment]
You're passing a null for the world parameter from what I'm seeing. Did you set the location of the NPC correctly?
Perhaps I'd be helpful if you posted a snippet with the code you're using to spawn the NPC.

**Comment by JitseB** [comment]
Closed, no activity.
