### ISSUE TITLE
PlayerLoginEvent | Cannot Interact with NPC while nicked.

### ISSUE THREAD

**Issue by Chibilena** [MinecraftLibraries/NPCLib#132]
In Paper you have the option to change the player profile such as the nickname or skin via AsyncPlayerPreLoginEvent, but if you use this you can no longer interact with any `NPC.

     
```
	@EventHandler //Paper Methode
	public void AsyncPlayerPreLogin(AsyncPlayerPreLoginEvent event) {
 
		UUID uuid = event.getUniqueId();		
		String nickname = "test";
 
		event.setPlayerProfile(Bukkit.createProfile(uuid, nickname));
 
	}
```
 
```
[09:09:39 ERROR]: Could not pass event PlayerLoginEvent to Citybuild v1.0 //Error
java.lang.NullPointerException: null
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:1.8.0_272]
        at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_272]
        at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_272]
        at com.comphenix.tinyprotocol.Reflection$1.get(Reflection.java:153) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol.getChannel(TinyProtocol.java:279) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol.access$900(TinyProtocol.java:30) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol$5.onPlayerLogin(TinyProtocol.java:166) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-354]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-354]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-354]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.PlayerList.attemptLogin(PlayerList.java:667) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:148) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:66) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1381) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-354]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-354]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

**Comment by JitseB** [comment]
Please use the provided issue template.
