### ISSUE TITLE
Error spam and lag

### ISSUE THREAD

**Issue by Endrjuu** [MinecraftLibraries/NPCLib#89]
`[10:04:35] [Netty Epoll Server IO #1/ERROR]: NPCLib Error in onPacketInAsync().
java.lang.NullPointerException
	at net.jitse.npclib.internal.NPCBase.isShown(NPCBase.java:129) ~[Tools-1.0-SNAPSHOT.jar:?]
	at net.jitse.npclib.listeners.PacketListener.handleInteractPacket(PacketListener.java:65) ~[Tools-1.0-SNAPSHOT.jar:?]
	at net.jitse.npclib.listeners.PacketListener.access$000(PacketListener.java:25) ~[Tools-1.0-SNAPSHOT.jar:?]
	at net.jitse.npclib.listeners.PacketListener$1.onPacketInAsync(PacketListener.java:46) ~[Tools-1.0-SNAPSHOT.jar:?]
	at com.comphenix.tinyprotocol.TinyProtocol$PacketInterceptor.channelRead(TinyProtocol.java:310) [Tools-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:1.8.8-R0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[10:04:35] [Netty Epoll Server IO #1/ERROR]: NPCLib Error in onPacketInAsync().
java.lang.NullPointerException
[10:04:35] [Netty Epoll Server IO #1/ERROR]: NPCLib Error in onPacketInAsync().
java.lang.NullPointerException
[10:04:35] [Netty Epoll Server IO #1/ERROR]: NPCLib Error in onPacketInAsync().
java.lang.NullPointerException
[10:04:35] [Netty Epoll Server IO #1/ERROR]: NPCLib Error in onPacketInAsync().
java.lang.NullPointerException`

**Comment by Diszyyy** [comment]
same problem :s

**Comment by JitseB** [comment]
Please use the provided issue template. Without I can help you much less effectively.

To me it seems like the library is checking a player that is no longer recorded by the server. Can you verify this?

**Comment by JitseB** [comment]
So I've looked over the code where the nullpointer is thrown on. The object that I think is null is the player object, but this makes no sense at all. However, I could make a pre-release with this included as a check. Would anyone be interested in that?

**Comment by Diszyyy** [comment]
yes me

Op do 25 jun. 2020 om 22:48 schreef Jitse Boonstra <notifications@github.com

**Comment by ItsWind** [comment]
Can confirm this bug is still a problem. :(

**Comment by JitseB** [comment]
Does this issue still occur using one of the more recent builds of the library?

**Comment by JitseB** [comment]
No activity, closing issue.
