### ISSUE TITLE
NullPointer when i try to show the NPC

### ISSUE THREAD

**Issue by Traolian** [MinecraftLibraries/NPCLib#91]
Im getting a NullPointer in the show line...

public void addPlayer(Player player) {
NPC npc = npcLib.createNPC(Arrays.asList("§60 CPS"));
npc.setLocation(this.NPCLocation);
npc.show(player);

}

NPCLib JAR name
npclib-plugin-2.7.1-SNAPSHOT.jar

Server version
CraftBukkit version git-PaperSpigot-"4c7641d" (MC1.8.8) (Implementing API version 1.8.8-R0.1)

To Reproduce

    Used code 'npc.show(player);'

Expected behavior
I want to make an NPC for a CPS Count

**Comment by Traolian** [comment]
In line 76 there isn't the method "sendShowPackets" in this line there is the method "sendHidePackets"..
```
Caused by: java.lang.NullPointerException
at net.jitse.npclib.nms.v1_8_R3.NPC_v1_8_R3.sendShowPackets(NPC_v1_8_R3.java:76) ~[?:?]
at net.jitse.npclib.internal.NPCBase.show(NPCBase.java:199) ~[?:?]
at net.jitse.npclib.internal.NPCBase.show(NPCBase.java:172) ~[?:?]
```
```
76:  public void sendHidePackets(Player player) {
77:         PlayerConnection playerConnection = ((CraftPlayer)player).getHandle().playerConnection;
78:         playerConnection.sendPacket(this.packetPlayOutEntityDestroy);
79:         playerConnection.sendPacket(this.packetPlayOutPlayerInfoRemove);
80:         this.hologram.hide(player);
81:     }
```

**Comment by Traolian** [comment]
I looked through the codes and came to the code:

```java
hologram.show(player);
```

So hologram would be null...
